url: "https://colmenacowork.es"
baseurl: ""
title: "La Colmena"
lang: "es"

url_en: "https://colmenacowork.es/en/"

email: info@colmenacowork.es

# Include Netlify redirects
include: [_redirects]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->

tagline: "Espacio de Coworking en La Sierra de Cádiz"
permalink: /:title

description: "La Colmena es un espacio de coworking en Prado del Rey, en la Sierra de Cádiz."
# English description in /en/index.md

twitter:
  card: summary_large_image

noindex_urls:
  - /offline

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer

# Translations
t:
  es:
    logo_link_title_attr: "Inicio"
    toggle_menu_aria_label: "Abrir o cerrar navigación"
    footer_about: "La Colmena es un espacio de coworking rural situado en Prado del Rey, en la Sierra de Cádiz."
    illustrations_by: "Ilustraciones por"
    logo_alt: "Logo de La Colmena espacio de coworking"
    skip_link_anchor_text: "Saltar al contenido principal"
    skip_link_target_anchor_text: "Inicio del contenido principal"
    main_menu_aria_label: "Navigación principal"
    language_switcher_aria_label: "Cambiar idioma"
    main_menu:
      inicio:
        name: "Inicio"
        url: "/"
      quienes_somos:
        name: "Quiénes Somos"
        url: "/quienes-somos"
      precios:
        name: "Precios"
        url: "/precios"
      blog:
        name: "Blog"
        url: "/blog"
      faq:
        name: "Preguntas Frecuentes"
        url: "/#faq"
      eventos:
        name: "Eventos"
        url: "/eventos"
      contacto:
        name: "Contacto"
        url: "/contacto"
    legal_menu:
      cookies:
        name: "Cookies"
        url: "/cookies"
      privacidad:
        name: "Política de Privacidad"
        url: "/politica-de-privacidad"
    alt:
      prado-del-rey-plaza: La Plaza de la Constitución y Parroquia Nuestra Señora del Carmen, Prado del Rey
      chill-people: Personas relajándose en la zona de descanso
      kitchen-2023: Nuestra pequeña cocina
      office-from-back: El espacio principal de coworking
      hexagons-wall: Primer plano de hexágonos en la pared
      bookshelf: Primer plano de la estantería
      meeting-room-people: Un grupo de personas en una reunión en nuestra sala de reuniones
      prado-sunset: Atardecer sobre Prado del Rey
      door-sign: Primer plano de nuestro cartel en la puerta principal
      chill: La zona de descanso
      hot-desks-low: Nuestros escritorios compartidos
      kettle: Primer plano de la tetera, té y taza
  en:
    logo_link_title_attr: "Home"
    toggle_menu_aria_label: "Open or close menu"
    footer_about: "La Colmena is a rural coworking space in Prado del Rey, Sierra de Cadiz."
    illustrations_by: "Illustrations by"
    logo_alt: "La Colmena coworking space logo"
    skip_link_anchor_text: "Skip to main content"
    skip_link_target_anchor_text: "Start of main content"
    main_menu_aria_label: "Main menu"
    language_switcher_aria_label: "Change language"
    main_menu:
      inicio:
        name: "Home"
        url: "/en/"
      quienes_somos:
        name: "About"
        url: "/about"
      precios:
        name: "Prices"
        url: "/prices"
      blog:
        name: "Blog"
        url: "/en/blog"
      faq:
        name: "FAQ"
        url: "/en/#faq"
      eventos:
        name: "Events"
        url: "/eventos"
      contacto:
        name: "Contact"
        url: "/contact"
    legal_menu:
      cookies:
        name: "Cookies"
        url: "/en/cookies"
      privacidad:
        name: "Privacy Policy"
        url: "/privacy-policy"
    alt:
      prado-del-rey-plaza: The Plaza de la Constitución y church, Nuestra Señora del Carmen, Prado del Rey
      chill-people: People hanging out in the chill out area
      kitchen-2023: Our little kitchen
      office-from-back: The main coworking space
      hexagons-wall: Close up of hexagons on wall
      bookshelf: Close up of the bookshelf
      meeting-room-people: A group of people having a meeting in our meeting room
      prado-sunset: Sunset over Prado del Rey
      door-sign: Close up of our front door sandwich board
      chill: The chill out area
      hot-desks-low: Our hot desks
      kettle: Close up of the kettle, tea and mug
