url: "https://colmenacowork.es"
baseurl: ""
title: "La Colmena Espacio de Coworking"
lang: "es"

tagline: "Espacio de Coworking en Prado del Rey, Cádiz"
permalink: /blog/:categories/:year/:month/:day/:title

description: "Estamos planeando abrir La Colmena un espacio de coworking en Prado del Rey, Cádiz. Un espacio coworking donde compartir ideas, desarrollar y mejorar tus ideas de negocio"
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer

# Translations
t:
  es:
    ilustraciones_por: "Ilustraciones por"
  en:
    ilustraciones_por: "Illustrations by"
