url: "https://colmenacowork.es" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "La Colmena | Coworking Rural" # the name of your site, e.g. ACME Corp.
lang: "es_ES"

tagline: "Espacio de coworking in Prado del Rey, Cádiz"
permalink: /blog/:categories/:year/:month/:day/:title

description: "La Colmena sera un espacio de coworking rural, situado en Prado del Rey, Cádiz, Andalucía, abriendo se en 2021"
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer
