url: "https://colmenacowork.es"
baseurl: ""
title: "La Colmena"
lang: "es"

url_en: "https://colmenacowork.es/en/"

email: info@colmenacowork.es

# temp for faster building locally
# exclude:
#   - assets/fonts

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->

tagline: "Espacio de Coworking en La Sierra de Cádiz"
permalink: /:title

description: "Estamos al punto de abrir La Colmena un espacio de coworking en La Sierra de Cádiz. Un espacio coworking donde compartir ideas y desarrollar tus ideas de negocio"
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer

# Translations
t:
  es:
    logo_link_title_attr: "Inicio"
    toggle_menu_aria_label: "Abrir o cerrar navigación"
    footer_about: "La Colmena es un espacio de coworking rural situado en Prado del Rey, la Sierra de Cádiz. El proyecto tiene
    previsto abrir sus puertas a principios del 2022."
    footer_tagline: "Espacio de coworking en La Sierra de Cádiz"
    illustrations_by: "Ilustraciones por"
    logo_alt: "Logo de La Colmena espacio de coworking"
    skip_link_anchor_text: "Saltar al contenido principal"
    skip_link_target_anchor_text: "Inicio del contenido principal"
    main_menu_aria_label: "Navigación principal"
    language_switcher_aria_label: "Cambiar idioma"
    main_menu:
      blog:
        name: "Blog"
        url: "/blog"
      contacto:
        name: "Contacto"
        url: "mailto:info@colmenacowork.es"
  en:
    logo_link_title_attr: "Home"
    toggle_menu_aria_label: "Open or close menu"
    footer_about: "La Colmena is a rural coworking space located in Prado del Rey, the Sierra de Cadiz. The project aims to open its doors at the start of 2022."
    footer_tagline: "Coworking space in the Sierra de Cadiz"
    illustrations_by: "Illustrations by"
    logo_alt: "La Colmena coworking space logo"
    skip_link_anchor_text: "Skip to main content"
    skip_link_target_anchor_text: "Start of main content"
    main_menu_aria_label: "Main menu"
    language_switcher_aria_label: "Change language"
    main_menu:
      blog:
        name: "Blog"
        url: "/en/blog"
      contacto:
        name: "Contact"
        url: "mailto:info@colmenacowork.es"
