url: "https://colmenacowork.es" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "La Colmena Coworking Rural" # the name of your site, e.g. ACME Corp.
lang: "es_ES"

tagline: "Coworking en Prado del Rey"
permalink: /blog/:categories/:year/:month/:day/:title

description: "Siempre y cuando la situación de COVID mejore, La Colmena Coworking en Prado del Rey
tiene previsto abrir sus puertas en 2021."
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer
