url: "https://colmenacowork.es" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "La Colmena Coworking Rural" # the name of your site, e.g. ACME Corp.
lang: "es_ES"

tagline: "Coworking en Prado del Rey"
permalink: /blog/:categories/:year/:month/:day/:title

description: "Estamos planeando abrir La Colmena Coworking, una oficina compartida en Prado del Rey. Un lugar donde compartir ideas, desarrollar y mejorar tus ideas de negocio"
twitter:
  card: summary_large_image

sass:
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer
